<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.meteor</groupId>
        <artifactId>meteor</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <description>数据分析模块 port:8088</description>

    <artifactId>meteor-operation-analytics</artifactId>


    <dependencies>
        <dependency>
            <groupId>com.meteor</groupId>
            <artifactId>meteor-common-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor</groupId>
            <artifactId>meteor-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor</groupId>
            <artifactId>meteor-mq-topology-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor</groupId>
            <artifactId>meteor-mq-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor</groupId>
            <artifactId>meteor-mq-contract</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor</groupId>
            <artifactId>meteor-mp-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
    </dependencies>
</project>